### ISSUE TITLE
Connect to DBus

### ISSUE THREAD

**Issue by N1coc4colA** [linuxdeepin/deepin-menu#19]
Hello, I'm looking for how to use it... Can you do a little tutorial for me on how to do an interface to access it, register, access menu, get json data that we need to use trough dbus? and can you change object name by something more simple: the PID, if you use it, we can get focused window's PID and get it's menu... Can you help me so?

**Comment by BLumia** [comment]
Hi and which programming language/UI framework did you use? If you are using Qt/DTK, we suggest you use QMenu directly as normal Qt app do and it will apply DDE menu look'n'feel without doing any extra change. If you are using other toolkit, consider take [this](https://github.com/linuxdeepin/deepin-terminal/blob/master/lib/menu.vala) as a reference. 

FYI currently only `deepin-terminal` (GTK app) and the window manager (whatever `dde-kwin` or `deepin-wm`) are using `deepin-menu` because it cannot use the menu drawn by the qt platform plugin, so if you are using Qt, it's strongly suggested to use DTK instead of using the `deepin-menu`.

**Comment by N1coc4colA** [comment]
OK, I understand more for what is it. Do you have a way to get a remote QObject (a QMenu) using dbus?

**Comment by BLumia** [comment]
I'm still not quite sure about your use case, so I just assume you would like to create a DDE/DTK style menu inside a Qt app, then I recommend you use DTK directly.

The following is a very simple demo snip you can test it out. Save it as `main.cpp` and run the following command to build it: 

``` shell
$ # you'll get `main.elf`
$ g++ main.cpp -o main.elf `pkg-config --libs Qt5Widgets dtkwidget --cflags` -fPIC
```

``` c++
#include <QMenu>
#include <DMainWindow>
#include <DApplication>

DWIDGET_USE_NAMESPACE

int main(int argc, char *argv[])
{
    DApplication::loadDXcbPlugin();

    DApplication app(argc, argv);

    DMainWindow w;
    w.show();

    QMenu menu;
    menu.addAction("Sample action");
    menu.exec();

    return app.exec();
}
```

This code will show you a new empty window and then also show you a menu at the top-left side of your screen (since we didn't pass any argument to the `QMenu::exec()` call).

But for your info, as you can see the above example didn't use the `deepin-menu` project at all, the look and feel of DTK app is made by [DDE Qt platform plugin](https://github.com/linuxdeepin/qt5integration), not by `deepin-menu`. The `deepin-menu` project is only for other projects which cannot use the Qt platform plugin.

**Comment by N1coc4colA** [comment]
You haven't understand... I know it about all the platform plugins (I worked on it to make users able to use their own theme at https://github.com/N1coc4colA/NUI-TEMPLATE) the thing that I mean is a global app menu that get QMenu trough DBus with DBusMenuImporter of libdbusmenu-qt or something like that (like on Gnome and KDE) now, I'm looking on kde applet that gets Qt window's menu but system Qt version is too old and the leasy ppa is break so... I have some errors that depends Qt version... Hoping that v20 will come soon. Ihave a question that isn't about the subject but did you change blur radius or give to developpers the choice to choose blur radius in DBlurEffectWidget?

**Comment by BLumia** [comment]
> You haven't understand... I know it about all the platform plugins (I worked on it to make users able to use their own theme at https://github.com/N1coc4colA/NUI-TEMPLATE) the thing that I mean is a global app menu that get QMenu trough DBus with DBusMenuImporter of libdbusmenu-qt or something like that (like on Gnome and KDE) now, I'm looking on kde applet that gets Qt window's menu but system Qt version is too old and the leasy ppa is break so... I have some errors that depends Qt version... Hoping that v20 will come soon.

The `deepin-menu` *may* (still not decided now) get deprecated if no other DDE apps are using it so I'm not sure if it's suitable to introduce the usage of `deepin-menu` dbus api. Take [this one from dde-dock codebase](https://github.com/linuxdeepin/dde-dock/blob/daed0fc57e2af518b1201cfe35400909d2bd06ed/plugins/tray/system-trays/systemtrayitem.cpp#L393-L425) as reference will be good.

>I have a question that isn't about the subject but did you change blur radius or give to developpers the choice to choose blur radius in DBlurEffectWidget?

I haven't look into the old dtk codebase (you can check it out by yourself by reading the DTK header file), in v20 DTK (DTK5) there are `DBlurEffectWidget::setBlurRectXRadius()` and `DBlurEffectWidget::setBlurRectYRadius()`.

**Comment by N1coc4colA** [comment]
The fuctions that you gave me don't work, it's RECT radius, it's like in QCss: border-radius ;)
Thank you for yourr help. Before release v20, you shoul make org.canonical.AppMenu.Registrar portation on Deepin, you'll can make insane things with it or make users able to choose their own dstyleplugin theme...
